name: frontend_quizzical
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  uuid: ^4.5.0
  url_launcher: ^6.3.0
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
